# Generated by Django 2.2.10 on 2021-05-21 09:13

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('title', models.CharField(
                    db_index=True,
                    help_text='Название может быть'
                    'максимальной длиной до 255 символов.',
                    max_length=255,
                    verbose_name='Название опроса')),
                ('start', models.DateField(
                    auto_now_add=True,
                    verbose_name='Начало опроса')),
                ('ending', models.DateField(
                    blank=True,
                    null=True,
                    verbose_name='Окончание опроса')),
                ('description', models.TextField(
                    blank=True,
                    help_text='Описание опроса.',
                    verbose_name='Описание')),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Организатор')),
            ],
            options={
                'verbose_name_plural': 'Опросы',
                'ordering': ('-start',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('text', models.TextField(
                    db_index=True,
                    verbose_name='Вопрос')),
                ('types', models.CharField(choices=[
                    ('TEXT', 'Запишите верный ответ'),
                    ('CHOICE', 'Один правильный ответ'),
                    ('MULTICHOICE', 'Несколько правильных ответов')],
                    default='TEXT',
                    max_length=30,
                    verbose_name='Тип вопроса')),
                ('poll', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='questions',
                    to='api.Poll',
                    verbose_name='Опрос')),
            ],
            options={
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('start', models.DateField(
                    default=datetime.date(2021, 5, 21),
                    editable=False,
                    verbose_name='Старт участия')),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Участник')),
                ('poll', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='poll_choise',
                    to='api.Poll',
                    verbose_name='Опрос')),
            ],
            options={
                'verbose_name_plural': 'Участники вопросов',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('correct_answer', models.CharField(
                    blank=True,
                    max_length=10,
                    null=True,
                    verbose_name='Правильный ответ')),
                ('answer', models.CharField(
                    blank=True,
                    max_length=256,
                    null=True,
                    verbose_name='Ответ автора')),
                ('choise', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='cards',
                    to='api.Choice',
                    verbose_name='Опрос')),
                ('question', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='api.Question',
                    verbose_name='Вопрос')),
            ],
            options={
                'verbose_name_plural': 'Карточка автора',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('number', models.SmallIntegerField(
                    verbose_name='Номер ответа')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('correct', models.BooleanField(
                    default=False, verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(
                    help_text='Ответы к данному вопросу',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='answers',
                    to='api.Question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
